dir: "{{.InterfaceDirRelative}}"
inpackage: true
filename: "mock_{{.InterfaceNameSnake}}.go"
mock-build-tags: "!release"
disable-version-string: true
packages:
  github.com/gemyago/oke-gateway-api/internal/app:
    interfaces:
      k8sClient:
  log/slog:
    interfaces:
      Handler:
        config:
          inpackage: false
          outpkg: 'diag'
          dir: 'internal/diag'
          filename: "mock_slog_handler.go"
          mockname: MockSlogHandler