apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "oke-gateway-api-controller.fullname" . }}-role
  labels:
    {{- include "oke-gateway-api-controller.labels" . | nindent 4 }}
rules:
# Permissions to watch and update Gateway API resources
- apiGroups: ["gateway.networking.k8s.io"]
  # Add other relevant route types like TCPRoute, UDPRoute, TLSRoute if the controller supports them
  resources: ["gatewayclasses", "gateways", "httproutes", "referencegrants"]
  verbs: ["get", "list", "watch", "update", "patch"] # Read access + update/patch for finalizers/annotations
- apiGroups: ["gateway.networking.k8s.io"]
  # Add status subresources for other supported route types
  resources: ["gatewayclasses/status", "gateways/status", "httproutes/status"]
  verbs: ["update", "patch"] # Update status
# Permissions to read necessary core resources for OCI LB configuration
- apiGroups: [""]
  resources: ["services", "endpoints", "secrets", "nodes"]
  verbs: ["get", "list", "watch"] # Read-only access
# Permissions for leader election
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 