apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "oke-gateway-api-controller.fullname" . }}-binding
  labels:
    {{- include "oke-gateway-api-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "oke-gateway-api-controller.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "oke-gateway-api-controller.serviceAccountName" . }}
  namespace: {{ include "oke-gateway-api-controller.namespace" . }} 