apiVersion: v2
name: oke-gateway-api-controller
description: A Helm chart for the OKE Gateway API Controller

type: application

# Incremented automatically with each release.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# Set automatically to the release version by release tool.
appVersion: "main"