{{- if .Values.serviceGatewayRoutes }}
{{- range .Values.serviceGatewayRoutes }}
{{- if .enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "api-service.fullname" $ }}-{{ .nameSuffix }}
spec:
  parentRefs:
    - name: {{ .gatewayName }}
      namespace: {{ .namespace }}
      sectionName: {{ .sectionName }}
  rules:
    {{- range .matchRules }}
    - matches:
        {{- toYaml .matches | nindent 8 }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "api-service.fullname" $ }}
          port: {{ $.Values.service.port }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}