// Code generated by mockery. DO NOT EDIT.

//go:build !release

package app

import (
	context "context"

	loadbalancer "github.com/oracle/oci-go-sdk/v65/loadbalancer"
	mock "github.com/stretchr/testify/mock"
)

// MockociLoadBalancerClient is an autogenerated mock type for the ociLoadBalancerClient type
type MockociLoadBalancerClient struct {
	mock.Mock
}

type MockociLoadBalancerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockociLoadBalancerClient) EXPECT() *MockociLoadBalancerClient_Expecter {
	return &MockociLoadBalancerClient_Expecter{mock: &_m.Mock}
}

// CreateBackend provides a mock function with given fields: ctx, request
func (_m *MockociLoadBalancerClient) CreateBackend(ctx context.Context, request loadbalancer.CreateBackendRequest) (loadbalancer.CreateBackendResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackend")
	}

	var r0 loadbalancer.CreateBackendResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.CreateBackendRequest) (loadbalancer.CreateBackendResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.CreateBackendRequest) loadbalancer.CreateBackendResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(loadbalancer.CreateBackendResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, loadbalancer.CreateBackendRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerClient_CreateBackend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackend'
type MockociLoadBalancerClient_CreateBackend_Call struct {
	*mock.Call
}

// CreateBackend is a helper method to define mock.On call
//   - ctx context.Context
//   - request loadbalancer.CreateBackendRequest
func (_e *MockociLoadBalancerClient_Expecter) CreateBackend(ctx interface{}, request interface{}) *MockociLoadBalancerClient_CreateBackend_Call {
	return &MockociLoadBalancerClient_CreateBackend_Call{Call: _e.mock.On("CreateBackend", ctx, request)}
}

func (_c *MockociLoadBalancerClient_CreateBackend_Call) Run(run func(ctx context.Context, request loadbalancer.CreateBackendRequest)) *MockociLoadBalancerClient_CreateBackend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(loadbalancer.CreateBackendRequest))
	})
	return _c
}

func (_c *MockociLoadBalancerClient_CreateBackend_Call) Return(response loadbalancer.CreateBackendResponse, err error) *MockociLoadBalancerClient_CreateBackend_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociLoadBalancerClient_CreateBackend_Call) RunAndReturn(run func(context.Context, loadbalancer.CreateBackendRequest) (loadbalancer.CreateBackendResponse, error)) *MockociLoadBalancerClient_CreateBackend_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBackendSet provides a mock function with given fields: ctx, request
func (_m *MockociLoadBalancerClient) CreateBackendSet(ctx context.Context, request loadbalancer.CreateBackendSetRequest) (loadbalancer.CreateBackendSetResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackendSet")
	}

	var r0 loadbalancer.CreateBackendSetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.CreateBackendSetRequest) (loadbalancer.CreateBackendSetResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.CreateBackendSetRequest) loadbalancer.CreateBackendSetResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(loadbalancer.CreateBackendSetResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, loadbalancer.CreateBackendSetRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerClient_CreateBackendSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackendSet'
type MockociLoadBalancerClient_CreateBackendSet_Call struct {
	*mock.Call
}

// CreateBackendSet is a helper method to define mock.On call
//   - ctx context.Context
//   - request loadbalancer.CreateBackendSetRequest
func (_e *MockociLoadBalancerClient_Expecter) CreateBackendSet(ctx interface{}, request interface{}) *MockociLoadBalancerClient_CreateBackendSet_Call {
	return &MockociLoadBalancerClient_CreateBackendSet_Call{Call: _e.mock.On("CreateBackendSet", ctx, request)}
}

func (_c *MockociLoadBalancerClient_CreateBackendSet_Call) Run(run func(ctx context.Context, request loadbalancer.CreateBackendSetRequest)) *MockociLoadBalancerClient_CreateBackendSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(loadbalancer.CreateBackendSetRequest))
	})
	return _c
}

func (_c *MockociLoadBalancerClient_CreateBackendSet_Call) Return(response loadbalancer.CreateBackendSetResponse, err error) *MockociLoadBalancerClient_CreateBackendSet_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociLoadBalancerClient_CreateBackendSet_Call) RunAndReturn(run func(context.Context, loadbalancer.CreateBackendSetRequest) (loadbalancer.CreateBackendSetResponse, error)) *MockociLoadBalancerClient_CreateBackendSet_Call {
	_c.Call.Return(run)
	return _c
}

// CreateHostname provides a mock function with given fields: ctx, request
func (_m *MockociLoadBalancerClient) CreateHostname(ctx context.Context, request loadbalancer.CreateHostnameRequest) (loadbalancer.CreateHostnameResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateHostname")
	}

	var r0 loadbalancer.CreateHostnameResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.CreateHostnameRequest) (loadbalancer.CreateHostnameResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.CreateHostnameRequest) loadbalancer.CreateHostnameResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(loadbalancer.CreateHostnameResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, loadbalancer.CreateHostnameRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerClient_CreateHostname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHostname'
type MockociLoadBalancerClient_CreateHostname_Call struct {
	*mock.Call
}

// CreateHostname is a helper method to define mock.On call
//   - ctx context.Context
//   - request loadbalancer.CreateHostnameRequest
func (_e *MockociLoadBalancerClient_Expecter) CreateHostname(ctx interface{}, request interface{}) *MockociLoadBalancerClient_CreateHostname_Call {
	return &MockociLoadBalancerClient_CreateHostname_Call{Call: _e.mock.On("CreateHostname", ctx, request)}
}

func (_c *MockociLoadBalancerClient_CreateHostname_Call) Run(run func(ctx context.Context, request loadbalancer.CreateHostnameRequest)) *MockociLoadBalancerClient_CreateHostname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(loadbalancer.CreateHostnameRequest))
	})
	return _c
}

func (_c *MockociLoadBalancerClient_CreateHostname_Call) Return(response loadbalancer.CreateHostnameResponse, err error) *MockociLoadBalancerClient_CreateHostname_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociLoadBalancerClient_CreateHostname_Call) RunAndReturn(run func(context.Context, loadbalancer.CreateHostnameRequest) (loadbalancer.CreateHostnameResponse, error)) *MockociLoadBalancerClient_CreateHostname_Call {
	_c.Call.Return(run)
	return _c
}

// CreateListener provides a mock function with given fields: ctx, request
func (_m *MockociLoadBalancerClient) CreateListener(ctx context.Context, request loadbalancer.CreateListenerRequest) (loadbalancer.CreateListenerResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateListener")
	}

	var r0 loadbalancer.CreateListenerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.CreateListenerRequest) (loadbalancer.CreateListenerResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.CreateListenerRequest) loadbalancer.CreateListenerResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(loadbalancer.CreateListenerResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, loadbalancer.CreateListenerRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerClient_CreateListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateListener'
type MockociLoadBalancerClient_CreateListener_Call struct {
	*mock.Call
}

// CreateListener is a helper method to define mock.On call
//   - ctx context.Context
//   - request loadbalancer.CreateListenerRequest
func (_e *MockociLoadBalancerClient_Expecter) CreateListener(ctx interface{}, request interface{}) *MockociLoadBalancerClient_CreateListener_Call {
	return &MockociLoadBalancerClient_CreateListener_Call{Call: _e.mock.On("CreateListener", ctx, request)}
}

func (_c *MockociLoadBalancerClient_CreateListener_Call) Run(run func(ctx context.Context, request loadbalancer.CreateListenerRequest)) *MockociLoadBalancerClient_CreateListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(loadbalancer.CreateListenerRequest))
	})
	return _c
}

func (_c *MockociLoadBalancerClient_CreateListener_Call) Return(response loadbalancer.CreateListenerResponse, err error) *MockociLoadBalancerClient_CreateListener_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociLoadBalancerClient_CreateListener_Call) RunAndReturn(run func(context.Context, loadbalancer.CreateListenerRequest) (loadbalancer.CreateListenerResponse, error)) *MockociLoadBalancerClient_CreateListener_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackendSet provides a mock function with given fields: ctx, request
func (_m *MockociLoadBalancerClient) GetBackendSet(ctx context.Context, request loadbalancer.GetBackendSetRequest) (loadbalancer.GetBackendSetResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetBackendSet")
	}

	var r0 loadbalancer.GetBackendSetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.GetBackendSetRequest) (loadbalancer.GetBackendSetResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.GetBackendSetRequest) loadbalancer.GetBackendSetResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(loadbalancer.GetBackendSetResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, loadbalancer.GetBackendSetRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerClient_GetBackendSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackendSet'
type MockociLoadBalancerClient_GetBackendSet_Call struct {
	*mock.Call
}

// GetBackendSet is a helper method to define mock.On call
//   - ctx context.Context
//   - request loadbalancer.GetBackendSetRequest
func (_e *MockociLoadBalancerClient_Expecter) GetBackendSet(ctx interface{}, request interface{}) *MockociLoadBalancerClient_GetBackendSet_Call {
	return &MockociLoadBalancerClient_GetBackendSet_Call{Call: _e.mock.On("GetBackendSet", ctx, request)}
}

func (_c *MockociLoadBalancerClient_GetBackendSet_Call) Run(run func(ctx context.Context, request loadbalancer.GetBackendSetRequest)) *MockociLoadBalancerClient_GetBackendSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(loadbalancer.GetBackendSetRequest))
	})
	return _c
}

func (_c *MockociLoadBalancerClient_GetBackendSet_Call) Return(response loadbalancer.GetBackendSetResponse, err error) *MockociLoadBalancerClient_GetBackendSet_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociLoadBalancerClient_GetBackendSet_Call) RunAndReturn(run func(context.Context, loadbalancer.GetBackendSetRequest) (loadbalancer.GetBackendSetResponse, error)) *MockociLoadBalancerClient_GetBackendSet_Call {
	_c.Call.Return(run)
	return _c
}

// GetHostname provides a mock function with given fields: ctx, request
func (_m *MockociLoadBalancerClient) GetHostname(ctx context.Context, request loadbalancer.GetHostnameRequest) (loadbalancer.GetHostnameResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetHostname")
	}

	var r0 loadbalancer.GetHostnameResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.GetHostnameRequest) (loadbalancer.GetHostnameResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.GetHostnameRequest) loadbalancer.GetHostnameResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(loadbalancer.GetHostnameResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, loadbalancer.GetHostnameRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerClient_GetHostname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHostname'
type MockociLoadBalancerClient_GetHostname_Call struct {
	*mock.Call
}

// GetHostname is a helper method to define mock.On call
//   - ctx context.Context
//   - request loadbalancer.GetHostnameRequest
func (_e *MockociLoadBalancerClient_Expecter) GetHostname(ctx interface{}, request interface{}) *MockociLoadBalancerClient_GetHostname_Call {
	return &MockociLoadBalancerClient_GetHostname_Call{Call: _e.mock.On("GetHostname", ctx, request)}
}

func (_c *MockociLoadBalancerClient_GetHostname_Call) Run(run func(ctx context.Context, request loadbalancer.GetHostnameRequest)) *MockociLoadBalancerClient_GetHostname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(loadbalancer.GetHostnameRequest))
	})
	return _c
}

func (_c *MockociLoadBalancerClient_GetHostname_Call) Return(response loadbalancer.GetHostnameResponse, err error) *MockociLoadBalancerClient_GetHostname_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociLoadBalancerClient_GetHostname_Call) RunAndReturn(run func(context.Context, loadbalancer.GetHostnameRequest) (loadbalancer.GetHostnameResponse, error)) *MockociLoadBalancerClient_GetHostname_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoadBalancer provides a mock function with given fields: ctx, request
func (_m *MockociLoadBalancerClient) GetLoadBalancer(ctx context.Context, request loadbalancer.GetLoadBalancerRequest) (loadbalancer.GetLoadBalancerResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetLoadBalancer")
	}

	var r0 loadbalancer.GetLoadBalancerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.GetLoadBalancerRequest) (loadbalancer.GetLoadBalancerResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.GetLoadBalancerRequest) loadbalancer.GetLoadBalancerResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(loadbalancer.GetLoadBalancerResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, loadbalancer.GetLoadBalancerRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerClient_GetLoadBalancer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoadBalancer'
type MockociLoadBalancerClient_GetLoadBalancer_Call struct {
	*mock.Call
}

// GetLoadBalancer is a helper method to define mock.On call
//   - ctx context.Context
//   - request loadbalancer.GetLoadBalancerRequest
func (_e *MockociLoadBalancerClient_Expecter) GetLoadBalancer(ctx interface{}, request interface{}) *MockociLoadBalancerClient_GetLoadBalancer_Call {
	return &MockociLoadBalancerClient_GetLoadBalancer_Call{Call: _e.mock.On("GetLoadBalancer", ctx, request)}
}

func (_c *MockociLoadBalancerClient_GetLoadBalancer_Call) Run(run func(ctx context.Context, request loadbalancer.GetLoadBalancerRequest)) *MockociLoadBalancerClient_GetLoadBalancer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(loadbalancer.GetLoadBalancerRequest))
	})
	return _c
}

func (_c *MockociLoadBalancerClient_GetLoadBalancer_Call) Return(response loadbalancer.GetLoadBalancerResponse, err error) *MockociLoadBalancerClient_GetLoadBalancer_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociLoadBalancerClient_GetLoadBalancer_Call) RunAndReturn(run func(context.Context, loadbalancer.GetLoadBalancerRequest) (loadbalancer.GetLoadBalancerResponse, error)) *MockociLoadBalancerClient_GetLoadBalancer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBackendSet provides a mock function with given fields: ctx, request
func (_m *MockociLoadBalancerClient) UpdateBackendSet(ctx context.Context, request loadbalancer.UpdateBackendSetRequest) (loadbalancer.UpdateBackendSetResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBackendSet")
	}

	var r0 loadbalancer.UpdateBackendSetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.UpdateBackendSetRequest) (loadbalancer.UpdateBackendSetResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, loadbalancer.UpdateBackendSetRequest) loadbalancer.UpdateBackendSetResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(loadbalancer.UpdateBackendSetResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, loadbalancer.UpdateBackendSetRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociLoadBalancerClient_UpdateBackendSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBackendSet'
type MockociLoadBalancerClient_UpdateBackendSet_Call struct {
	*mock.Call
}

// UpdateBackendSet is a helper method to define mock.On call
//   - ctx context.Context
//   - request loadbalancer.UpdateBackendSetRequest
func (_e *MockociLoadBalancerClient_Expecter) UpdateBackendSet(ctx interface{}, request interface{}) *MockociLoadBalancerClient_UpdateBackendSet_Call {
	return &MockociLoadBalancerClient_UpdateBackendSet_Call{Call: _e.mock.On("UpdateBackendSet", ctx, request)}
}

func (_c *MockociLoadBalancerClient_UpdateBackendSet_Call) Run(run func(ctx context.Context, request loadbalancer.UpdateBackendSetRequest)) *MockociLoadBalancerClient_UpdateBackendSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(loadbalancer.UpdateBackendSetRequest))
	})
	return _c
}

func (_c *MockociLoadBalancerClient_UpdateBackendSet_Call) Return(response loadbalancer.UpdateBackendSetResponse, err error) *MockociLoadBalancerClient_UpdateBackendSet_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociLoadBalancerClient_UpdateBackendSet_Call) RunAndReturn(run func(context.Context, loadbalancer.UpdateBackendSetRequest) (loadbalancer.UpdateBackendSetResponse, error)) *MockociLoadBalancerClient_UpdateBackendSet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockociLoadBalancerClient creates a new instance of MockociLoadBalancerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockociLoadBalancerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockociLoadBalancerClient {
	mock := &MockociLoadBalancerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
