// Code generated by mockery. DO NOT EDIT.

//go:build !release

package app

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockociLoadBalancerModel is an autogenerated mock type for the ociLoadBalancerModel type
type MockociLoadBalancerModel struct {
	mock.Mock
}

type MockociLoadBalancerModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockociLoadBalancerModel) EXPECT() *MockociLoadBalancerModel_Expecter {
	return &MockociLoadBalancerModel_Expecter{mock: &_m.Mock}
}

// programHttpListener provides a mock function with given fields: ctx, params
func (_m *MockociLoadBalancerModel) programHttpListener(ctx context.Context, params programHttpListenerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for programHttpListener")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, programHttpListenerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockociLoadBalancerModel_programHttpListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'programHttpListener'
type MockociLoadBalancerModel_programHttpListener_Call struct {
	*mock.Call
}

// programHttpListener is a helper method to define mock.On call
//   - ctx context.Context
//   - params programHttpListenerParams
func (_e *MockociLoadBalancerModel_Expecter) programHttpListener(ctx interface{}, params interface{}) *MockociLoadBalancerModel_programHttpListener_Call {
	return &MockociLoadBalancerModel_programHttpListener_Call{Call: _e.mock.On("programHttpListener", ctx, params)}
}

func (_c *MockociLoadBalancerModel_programHttpListener_Call) Run(run func(ctx context.Context, params programHttpListenerParams)) *MockociLoadBalancerModel_programHttpListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(programHttpListenerParams))
	})
	return _c
}

func (_c *MockociLoadBalancerModel_programHttpListener_Call) Return(_a0 error) *MockociLoadBalancerModel_programHttpListener_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockociLoadBalancerModel_programHttpListener_Call) RunAndReturn(run func(context.Context, programHttpListenerParams) error) *MockociLoadBalancerModel_programHttpListener_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockociLoadBalancerModel creates a new instance of MockociLoadBalancerModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockociLoadBalancerModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockociLoadBalancerModel {
	mock := &MockociLoadBalancerModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
