// Code generated by mockery. DO NOT EDIT.

//go:build !release

package app

import (
	context "context"

	networkloadbalancer "github.com/oracle/oci-go-sdk/v65/networkloadbalancer"
	mock "github.com/stretchr/testify/mock"
)

// MockociNetworkLoadBalancerClient is an autogenerated mock type for the ociNetworkLoadBalancerClient type
type MockociNetworkLoadBalancerClient struct {
	mock.Mock
}

type MockociNetworkLoadBalancerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockociNetworkLoadBalancerClient) EXPECT() *MockociNetworkLoadBalancerClient_Expecter {
	return &MockociNetworkLoadBalancerClient_Expecter{mock: &_m.Mock}
}

// CreateBackend provides a mock function with given fields: ctx, request
func (_m *MockociNetworkLoadBalancerClient) CreateBackend(ctx context.Context, request networkloadbalancer.CreateBackendRequest) (networkloadbalancer.CreateBackendResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackend")
	}

	var r0 networkloadbalancer.CreateBackendResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.CreateBackendRequest) (networkloadbalancer.CreateBackendResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.CreateBackendRequest) networkloadbalancer.CreateBackendResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(networkloadbalancer.CreateBackendResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, networkloadbalancer.CreateBackendRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociNetworkLoadBalancerClient_CreateBackend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackend'
type MockociNetworkLoadBalancerClient_CreateBackend_Call struct {
	*mock.Call
}

// CreateBackend is a helper method to define mock.On call
//   - ctx context.Context
//   - request networkloadbalancer.CreateBackendRequest
func (_e *MockociNetworkLoadBalancerClient_Expecter) CreateBackend(ctx interface{}, request interface{}) *MockociNetworkLoadBalancerClient_CreateBackend_Call {
	return &MockociNetworkLoadBalancerClient_CreateBackend_Call{Call: _e.mock.On("CreateBackend", ctx, request)}
}

func (_c *MockociNetworkLoadBalancerClient_CreateBackend_Call) Run(run func(ctx context.Context, request networkloadbalancer.CreateBackendRequest)) *MockociNetworkLoadBalancerClient_CreateBackend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networkloadbalancer.CreateBackendRequest))
	})
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_CreateBackend_Call) Return(response networkloadbalancer.CreateBackendResponse, err error) *MockociNetworkLoadBalancerClient_CreateBackend_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_CreateBackend_Call) RunAndReturn(run func(context.Context, networkloadbalancer.CreateBackendRequest) (networkloadbalancer.CreateBackendResponse, error)) *MockociNetworkLoadBalancerClient_CreateBackend_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBackendSet provides a mock function with given fields: ctx, request
func (_m *MockociNetworkLoadBalancerClient) CreateBackendSet(ctx context.Context, request networkloadbalancer.CreateBackendSetRequest) (networkloadbalancer.CreateBackendSetResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackendSet")
	}

	var r0 networkloadbalancer.CreateBackendSetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.CreateBackendSetRequest) (networkloadbalancer.CreateBackendSetResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.CreateBackendSetRequest) networkloadbalancer.CreateBackendSetResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(networkloadbalancer.CreateBackendSetResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, networkloadbalancer.CreateBackendSetRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociNetworkLoadBalancerClient_CreateBackendSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackendSet'
type MockociNetworkLoadBalancerClient_CreateBackendSet_Call struct {
	*mock.Call
}

// CreateBackendSet is a helper method to define mock.On call
//   - ctx context.Context
//   - request networkloadbalancer.CreateBackendSetRequest
func (_e *MockociNetworkLoadBalancerClient_Expecter) CreateBackendSet(ctx interface{}, request interface{}) *MockociNetworkLoadBalancerClient_CreateBackendSet_Call {
	return &MockociNetworkLoadBalancerClient_CreateBackendSet_Call{Call: _e.mock.On("CreateBackendSet", ctx, request)}
}

func (_c *MockociNetworkLoadBalancerClient_CreateBackendSet_Call) Run(run func(ctx context.Context, request networkloadbalancer.CreateBackendSetRequest)) *MockociNetworkLoadBalancerClient_CreateBackendSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networkloadbalancer.CreateBackendSetRequest))
	})
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_CreateBackendSet_Call) Return(response networkloadbalancer.CreateBackendSetResponse, err error) *MockociNetworkLoadBalancerClient_CreateBackendSet_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_CreateBackendSet_Call) RunAndReturn(run func(context.Context, networkloadbalancer.CreateBackendSetRequest) (networkloadbalancer.CreateBackendSetResponse, error)) *MockociNetworkLoadBalancerClient_CreateBackendSet_Call {
	_c.Call.Return(run)
	return _c
}

// CreateListener provides a mock function with given fields: ctx, request
func (_m *MockociNetworkLoadBalancerClient) CreateListener(ctx context.Context, request networkloadbalancer.CreateListenerRequest) (networkloadbalancer.CreateListenerResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateListener")
	}

	var r0 networkloadbalancer.CreateListenerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.CreateListenerRequest) (networkloadbalancer.CreateListenerResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.CreateListenerRequest) networkloadbalancer.CreateListenerResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(networkloadbalancer.CreateListenerResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, networkloadbalancer.CreateListenerRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociNetworkLoadBalancerClient_CreateListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateListener'
type MockociNetworkLoadBalancerClient_CreateListener_Call struct {
	*mock.Call
}

// CreateListener is a helper method to define mock.On call
//   - ctx context.Context
//   - request networkloadbalancer.CreateListenerRequest
func (_e *MockociNetworkLoadBalancerClient_Expecter) CreateListener(ctx interface{}, request interface{}) *MockociNetworkLoadBalancerClient_CreateListener_Call {
	return &MockociNetworkLoadBalancerClient_CreateListener_Call{Call: _e.mock.On("CreateListener", ctx, request)}
}

func (_c *MockociNetworkLoadBalancerClient_CreateListener_Call) Run(run func(ctx context.Context, request networkloadbalancer.CreateListenerRequest)) *MockociNetworkLoadBalancerClient_CreateListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networkloadbalancer.CreateListenerRequest))
	})
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_CreateListener_Call) Return(response networkloadbalancer.CreateListenerResponse, err error) *MockociNetworkLoadBalancerClient_CreateListener_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_CreateListener_Call) RunAndReturn(run func(context.Context, networkloadbalancer.CreateListenerRequest) (networkloadbalancer.CreateListenerResponse, error)) *MockociNetworkLoadBalancerClient_CreateListener_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBackend provides a mock function with given fields: ctx, request
func (_m *MockociNetworkLoadBalancerClient) DeleteBackend(ctx context.Context, request networkloadbalancer.DeleteBackendRequest) (networkloadbalancer.DeleteBackendResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBackend")
	}

	var r0 networkloadbalancer.DeleteBackendResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.DeleteBackendRequest) (networkloadbalancer.DeleteBackendResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.DeleteBackendRequest) networkloadbalancer.DeleteBackendResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(networkloadbalancer.DeleteBackendResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, networkloadbalancer.DeleteBackendRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociNetworkLoadBalancerClient_DeleteBackend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBackend'
type MockociNetworkLoadBalancerClient_DeleteBackend_Call struct {
	*mock.Call
}

// DeleteBackend is a helper method to define mock.On call
//   - ctx context.Context
//   - request networkloadbalancer.DeleteBackendRequest
func (_e *MockociNetworkLoadBalancerClient_Expecter) DeleteBackend(ctx interface{}, request interface{}) *MockociNetworkLoadBalancerClient_DeleteBackend_Call {
	return &MockociNetworkLoadBalancerClient_DeleteBackend_Call{Call: _e.mock.On("DeleteBackend", ctx, request)}
}

func (_c *MockociNetworkLoadBalancerClient_DeleteBackend_Call) Run(run func(ctx context.Context, request networkloadbalancer.DeleteBackendRequest)) *MockociNetworkLoadBalancerClient_DeleteBackend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networkloadbalancer.DeleteBackendRequest))
	})
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_DeleteBackend_Call) Return(response networkloadbalancer.DeleteBackendResponse, err error) *MockociNetworkLoadBalancerClient_DeleteBackend_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_DeleteBackend_Call) RunAndReturn(run func(context.Context, networkloadbalancer.DeleteBackendRequest) (networkloadbalancer.DeleteBackendResponse, error)) *MockociNetworkLoadBalancerClient_DeleteBackend_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBackendSet provides a mock function with given fields: ctx, request
func (_m *MockociNetworkLoadBalancerClient) DeleteBackendSet(ctx context.Context, request networkloadbalancer.DeleteBackendSetRequest) (networkloadbalancer.DeleteBackendSetResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBackendSet")
	}

	var r0 networkloadbalancer.DeleteBackendSetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.DeleteBackendSetRequest) (networkloadbalancer.DeleteBackendSetResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.DeleteBackendSetRequest) networkloadbalancer.DeleteBackendSetResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(networkloadbalancer.DeleteBackendSetResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, networkloadbalancer.DeleteBackendSetRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociNetworkLoadBalancerClient_DeleteBackendSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBackendSet'
type MockociNetworkLoadBalancerClient_DeleteBackendSet_Call struct {
	*mock.Call
}

// DeleteBackendSet is a helper method to define mock.On call
//   - ctx context.Context
//   - request networkloadbalancer.DeleteBackendSetRequest
func (_e *MockociNetworkLoadBalancerClient_Expecter) DeleteBackendSet(ctx interface{}, request interface{}) *MockociNetworkLoadBalancerClient_DeleteBackendSet_Call {
	return &MockociNetworkLoadBalancerClient_DeleteBackendSet_Call{Call: _e.mock.On("DeleteBackendSet", ctx, request)}
}

func (_c *MockociNetworkLoadBalancerClient_DeleteBackendSet_Call) Run(run func(ctx context.Context, request networkloadbalancer.DeleteBackendSetRequest)) *MockociNetworkLoadBalancerClient_DeleteBackendSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networkloadbalancer.DeleteBackendSetRequest))
	})
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_DeleteBackendSet_Call) Return(response networkloadbalancer.DeleteBackendSetResponse, err error) *MockociNetworkLoadBalancerClient_DeleteBackendSet_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_DeleteBackendSet_Call) RunAndReturn(run func(context.Context, networkloadbalancer.DeleteBackendSetRequest) (networkloadbalancer.DeleteBackendSetResponse, error)) *MockociNetworkLoadBalancerClient_DeleteBackendSet_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteListener provides a mock function with given fields: ctx, request
func (_m *MockociNetworkLoadBalancerClient) DeleteListener(ctx context.Context, request networkloadbalancer.DeleteListenerRequest) (networkloadbalancer.DeleteListenerResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteListener")
	}

	var r0 networkloadbalancer.DeleteListenerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.DeleteListenerRequest) (networkloadbalancer.DeleteListenerResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.DeleteListenerRequest) networkloadbalancer.DeleteListenerResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(networkloadbalancer.DeleteListenerResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, networkloadbalancer.DeleteListenerRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociNetworkLoadBalancerClient_DeleteListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteListener'
type MockociNetworkLoadBalancerClient_DeleteListener_Call struct {
	*mock.Call
}

// DeleteListener is a helper method to define mock.On call
//   - ctx context.Context
//   - request networkloadbalancer.DeleteListenerRequest
func (_e *MockociNetworkLoadBalancerClient_Expecter) DeleteListener(ctx interface{}, request interface{}) *MockociNetworkLoadBalancerClient_DeleteListener_Call {
	return &MockociNetworkLoadBalancerClient_DeleteListener_Call{Call: _e.mock.On("DeleteListener", ctx, request)}
}

func (_c *MockociNetworkLoadBalancerClient_DeleteListener_Call) Run(run func(ctx context.Context, request networkloadbalancer.DeleteListenerRequest)) *MockociNetworkLoadBalancerClient_DeleteListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networkloadbalancer.DeleteListenerRequest))
	})
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_DeleteListener_Call) Return(response networkloadbalancer.DeleteListenerResponse, err error) *MockociNetworkLoadBalancerClient_DeleteListener_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_DeleteListener_Call) RunAndReturn(run func(context.Context, networkloadbalancer.DeleteListenerRequest) (networkloadbalancer.DeleteListenerResponse, error)) *MockociNetworkLoadBalancerClient_DeleteListener_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetworkLoadBalancer provides a mock function with given fields: ctx, request
func (_m *MockociNetworkLoadBalancerClient) GetNetworkLoadBalancer(ctx context.Context, request networkloadbalancer.GetNetworkLoadBalancerRequest) (networkloadbalancer.GetNetworkLoadBalancerResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetNetworkLoadBalancer")
	}

	var r0 networkloadbalancer.GetNetworkLoadBalancerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.GetNetworkLoadBalancerRequest) (networkloadbalancer.GetNetworkLoadBalancerResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.GetNetworkLoadBalancerRequest) networkloadbalancer.GetNetworkLoadBalancerResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(networkloadbalancer.GetNetworkLoadBalancerResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, networkloadbalancer.GetNetworkLoadBalancerRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociNetworkLoadBalancerClient_GetNetworkLoadBalancer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetworkLoadBalancer'
type MockociNetworkLoadBalancerClient_GetNetworkLoadBalancer_Call struct {
	*mock.Call
}

// GetNetworkLoadBalancer is a helper method to define mock.On call
//   - ctx context.Context
//   - request networkloadbalancer.GetNetworkLoadBalancerRequest
func (_e *MockociNetworkLoadBalancerClient_Expecter) GetNetworkLoadBalancer(ctx interface{}, request interface{}) *MockociNetworkLoadBalancerClient_GetNetworkLoadBalancer_Call {
	return &MockociNetworkLoadBalancerClient_GetNetworkLoadBalancer_Call{Call: _e.mock.On("GetNetworkLoadBalancer", ctx, request)}
}

func (_c *MockociNetworkLoadBalancerClient_GetNetworkLoadBalancer_Call) Run(run func(ctx context.Context, request networkloadbalancer.GetNetworkLoadBalancerRequest)) *MockociNetworkLoadBalancerClient_GetNetworkLoadBalancer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networkloadbalancer.GetNetworkLoadBalancerRequest))
	})
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_GetNetworkLoadBalancer_Call) Return(response networkloadbalancer.GetNetworkLoadBalancerResponse, err error) *MockociNetworkLoadBalancerClient_GetNetworkLoadBalancer_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_GetNetworkLoadBalancer_Call) RunAndReturn(run func(context.Context, networkloadbalancer.GetNetworkLoadBalancerRequest) (networkloadbalancer.GetNetworkLoadBalancerResponse, error)) *MockociNetworkLoadBalancerClient_GetNetworkLoadBalancer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBackend provides a mock function with given fields: ctx, request
func (_m *MockociNetworkLoadBalancerClient) UpdateBackend(ctx context.Context, request networkloadbalancer.UpdateBackendRequest) (networkloadbalancer.UpdateBackendResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBackend")
	}

	var r0 networkloadbalancer.UpdateBackendResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.UpdateBackendRequest) (networkloadbalancer.UpdateBackendResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.UpdateBackendRequest) networkloadbalancer.UpdateBackendResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(networkloadbalancer.UpdateBackendResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, networkloadbalancer.UpdateBackendRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociNetworkLoadBalancerClient_UpdateBackend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBackend'
type MockociNetworkLoadBalancerClient_UpdateBackend_Call struct {
	*mock.Call
}

// UpdateBackend is a helper method to define mock.On call
//   - ctx context.Context
//   - request networkloadbalancer.UpdateBackendRequest
func (_e *MockociNetworkLoadBalancerClient_Expecter) UpdateBackend(ctx interface{}, request interface{}) *MockociNetworkLoadBalancerClient_UpdateBackend_Call {
	return &MockociNetworkLoadBalancerClient_UpdateBackend_Call{Call: _e.mock.On("UpdateBackend", ctx, request)}
}

func (_c *MockociNetworkLoadBalancerClient_UpdateBackend_Call) Run(run func(ctx context.Context, request networkloadbalancer.UpdateBackendRequest)) *MockociNetworkLoadBalancerClient_UpdateBackend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networkloadbalancer.UpdateBackendRequest))
	})
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_UpdateBackend_Call) Return(response networkloadbalancer.UpdateBackendResponse, err error) *MockociNetworkLoadBalancerClient_UpdateBackend_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_UpdateBackend_Call) RunAndReturn(run func(context.Context, networkloadbalancer.UpdateBackendRequest) (networkloadbalancer.UpdateBackendResponse, error)) *MockociNetworkLoadBalancerClient_UpdateBackend_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBackendSet provides a mock function with given fields: ctx, request
func (_m *MockociNetworkLoadBalancerClient) UpdateBackendSet(ctx context.Context, request networkloadbalancer.UpdateBackendSetRequest) (networkloadbalancer.UpdateBackendSetResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBackendSet")
	}

	var r0 networkloadbalancer.UpdateBackendSetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.UpdateBackendSetRequest) (networkloadbalancer.UpdateBackendSetResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.UpdateBackendSetRequest) networkloadbalancer.UpdateBackendSetResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(networkloadbalancer.UpdateBackendSetResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, networkloadbalancer.UpdateBackendSetRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociNetworkLoadBalancerClient_UpdateBackendSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBackendSet'
type MockociNetworkLoadBalancerClient_UpdateBackendSet_Call struct {
	*mock.Call
}

// UpdateBackendSet is a helper method to define mock.On call
//   - ctx context.Context
//   - request networkloadbalancer.UpdateBackendSetRequest
func (_e *MockociNetworkLoadBalancerClient_Expecter) UpdateBackendSet(ctx interface{}, request interface{}) *MockociNetworkLoadBalancerClient_UpdateBackendSet_Call {
	return &MockociNetworkLoadBalancerClient_UpdateBackendSet_Call{Call: _e.mock.On("UpdateBackendSet", ctx, request)}
}

func (_c *MockociNetworkLoadBalancerClient_UpdateBackendSet_Call) Run(run func(ctx context.Context, request networkloadbalancer.UpdateBackendSetRequest)) *MockociNetworkLoadBalancerClient_UpdateBackendSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networkloadbalancer.UpdateBackendSetRequest))
	})
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_UpdateBackendSet_Call) Return(response networkloadbalancer.UpdateBackendSetResponse, err error) *MockociNetworkLoadBalancerClient_UpdateBackendSet_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_UpdateBackendSet_Call) RunAndReturn(run func(context.Context, networkloadbalancer.UpdateBackendSetRequest) (networkloadbalancer.UpdateBackendSetResponse, error)) *MockociNetworkLoadBalancerClient_UpdateBackendSet_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateListener provides a mock function with given fields: ctx, request
func (_m *MockociNetworkLoadBalancerClient) UpdateListener(ctx context.Context, request networkloadbalancer.UpdateListenerRequest) (networkloadbalancer.UpdateListenerResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateListener")
	}

	var r0 networkloadbalancer.UpdateListenerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.UpdateListenerRequest) (networkloadbalancer.UpdateListenerResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, networkloadbalancer.UpdateListenerRequest) networkloadbalancer.UpdateListenerResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(networkloadbalancer.UpdateListenerResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, networkloadbalancer.UpdateListenerRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockociNetworkLoadBalancerClient_UpdateListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateListener'
type MockociNetworkLoadBalancerClient_UpdateListener_Call struct {
	*mock.Call
}

// UpdateListener is a helper method to define mock.On call
//   - ctx context.Context
//   - request networkloadbalancer.UpdateListenerRequest
func (_e *MockociNetworkLoadBalancerClient_Expecter) UpdateListener(ctx interface{}, request interface{}) *MockociNetworkLoadBalancerClient_UpdateListener_Call {
	return &MockociNetworkLoadBalancerClient_UpdateListener_Call{Call: _e.mock.On("UpdateListener", ctx, request)}
}

func (_c *MockociNetworkLoadBalancerClient_UpdateListener_Call) Run(run func(ctx context.Context, request networkloadbalancer.UpdateListenerRequest)) *MockociNetworkLoadBalancerClient_UpdateListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networkloadbalancer.UpdateListenerRequest))
	})
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_UpdateListener_Call) Return(response networkloadbalancer.UpdateListenerResponse, err error) *MockociNetworkLoadBalancerClient_UpdateListener_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockociNetworkLoadBalancerClient_UpdateListener_Call) RunAndReturn(run func(context.Context, networkloadbalancer.UpdateListenerRequest) (networkloadbalancer.UpdateListenerResponse, error)) *MockociNetworkLoadBalancerClient_UpdateListener_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockociNetworkLoadBalancerClient creates a new instance of MockociNetworkLoadBalancerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockociNetworkLoadBalancerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockociNetworkLoadBalancerClient {
	mock := &MockociNetworkLoadBalancerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
