// Code generated by mockery. DO NOT EDIT.

//go:build !release

package app

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockhttpBackendModel is an autogenerated mock type for the httpBackendModel type
type MockhttpBackendModel struct {
	mock.Mock
}

type MockhttpBackendModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockhttpBackendModel) EXPECT() *MockhttpBackendModel_Expecter {
	return &MockhttpBackendModel_Expecter{mock: &_m.Mock}
}

// identifyBackendsToUpdate provides a mock function with given fields: ctx, params
func (_m *MockhttpBackendModel) identifyBackendsToUpdate(ctx context.Context, params identifyBackendsToUpdateParams) (identifyBackendsToUpdateResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for identifyBackendsToUpdate")
	}

	var r0 identifyBackendsToUpdateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identifyBackendsToUpdateParams) (identifyBackendsToUpdateResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identifyBackendsToUpdateParams) identifyBackendsToUpdateResult); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(identifyBackendsToUpdateResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, identifyBackendsToUpdateParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockhttpBackendModel_identifyBackendsToUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'identifyBackendsToUpdate'
type MockhttpBackendModel_identifyBackendsToUpdate_Call struct {
	*mock.Call
}

// identifyBackendsToUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - params identifyBackendsToUpdateParams
func (_e *MockhttpBackendModel_Expecter) identifyBackendsToUpdate(ctx interface{}, params interface{}) *MockhttpBackendModel_identifyBackendsToUpdate_Call {
	return &MockhttpBackendModel_identifyBackendsToUpdate_Call{Call: _e.mock.On("identifyBackendsToUpdate", ctx, params)}
}

func (_c *MockhttpBackendModel_identifyBackendsToUpdate_Call) Run(run func(ctx context.Context, params identifyBackendsToUpdateParams)) *MockhttpBackendModel_identifyBackendsToUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(identifyBackendsToUpdateParams))
	})
	return _c
}

func (_c *MockhttpBackendModel_identifyBackendsToUpdate_Call) Return(_a0 identifyBackendsToUpdateResult, _a1 error) *MockhttpBackendModel_identifyBackendsToUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockhttpBackendModel_identifyBackendsToUpdate_Call) RunAndReturn(run func(context.Context, identifyBackendsToUpdateParams) (identifyBackendsToUpdateResult, error)) *MockhttpBackendModel_identifyBackendsToUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// syncRouteBackendRefEndpoints provides a mock function with given fields: ctx, params
func (_m *MockhttpBackendModel) syncRouteBackendRefEndpoints(ctx context.Context, params syncRouteBackendRefEndpointsParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for syncRouteBackendRefEndpoints")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, syncRouteBackendRefEndpointsParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockhttpBackendModel_syncRouteBackendRefEndpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'syncRouteBackendRefEndpoints'
type MockhttpBackendModel_syncRouteBackendRefEndpoints_Call struct {
	*mock.Call
}

// syncRouteBackendRefEndpoints is a helper method to define mock.On call
//   - ctx context.Context
//   - params syncRouteBackendRefEndpointsParams
func (_e *MockhttpBackendModel_Expecter) syncRouteBackendRefEndpoints(ctx interface{}, params interface{}) *MockhttpBackendModel_syncRouteBackendRefEndpoints_Call {
	return &MockhttpBackendModel_syncRouteBackendRefEndpoints_Call{Call: _e.mock.On("syncRouteBackendRefEndpoints", ctx, params)}
}

func (_c *MockhttpBackendModel_syncRouteBackendRefEndpoints_Call) Run(run func(ctx context.Context, params syncRouteBackendRefEndpointsParams)) *MockhttpBackendModel_syncRouteBackendRefEndpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(syncRouteBackendRefEndpointsParams))
	})
	return _c
}

func (_c *MockhttpBackendModel_syncRouteBackendRefEndpoints_Call) Return(_a0 error) *MockhttpBackendModel_syncRouteBackendRefEndpoints_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockhttpBackendModel_syncRouteBackendRefEndpoints_Call) RunAndReturn(run func(context.Context, syncRouteBackendRefEndpointsParams) error) *MockhttpBackendModel_syncRouteBackendRefEndpoints_Call {
	_c.Call.Return(run)
	return _c
}

// syncRouteEndpoints provides a mock function with given fields: ctx, params
func (_m *MockhttpBackendModel) syncRouteEndpoints(ctx context.Context, params syncRouteEndpointsParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for syncRouteEndpoints")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, syncRouteEndpointsParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockhttpBackendModel_syncRouteEndpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'syncRouteEndpoints'
type MockhttpBackendModel_syncRouteEndpoints_Call struct {
	*mock.Call
}

// syncRouteEndpoints is a helper method to define mock.On call
//   - ctx context.Context
//   - params syncRouteEndpointsParams
func (_e *MockhttpBackendModel_Expecter) syncRouteEndpoints(ctx interface{}, params interface{}) *MockhttpBackendModel_syncRouteEndpoints_Call {
	return &MockhttpBackendModel_syncRouteEndpoints_Call{Call: _e.mock.On("syncRouteEndpoints", ctx, params)}
}

func (_c *MockhttpBackendModel_syncRouteEndpoints_Call) Run(run func(ctx context.Context, params syncRouteEndpointsParams)) *MockhttpBackendModel_syncRouteEndpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(syncRouteEndpointsParams))
	})
	return _c
}

func (_c *MockhttpBackendModel_syncRouteEndpoints_Call) Return(_a0 error) *MockhttpBackendModel_syncRouteEndpoints_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockhttpBackendModel_syncRouteEndpoints_Call) RunAndReturn(run func(context.Context, syncRouteEndpointsParams) error) *MockhttpBackendModel_syncRouteEndpoints_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockhttpBackendModel creates a new instance of MockhttpBackendModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockhttpBackendModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockhttpBackendModel {
	mock := &MockhttpBackendModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
