// Code generated by mockery. DO NOT EDIT.

//go:build !release

package app

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockresourcesModel is an autogenerated mock type for the resourcesModel type
type MockresourcesModel struct {
	mock.Mock
}

type MockresourcesModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockresourcesModel) EXPECT() *MockresourcesModel_Expecter {
	return &MockresourcesModel_Expecter{mock: &_m.Mock}
}

// isConditionSet provides a mock function with given fields: params
func (_m *MockresourcesModel) isConditionSet(params isConditionSetParams) bool {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for isConditionSet")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(isConditionSetParams) bool); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockresourcesModel_isConditionSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isConditionSet'
type MockresourcesModel_isConditionSet_Call struct {
	*mock.Call
}

// isConditionSet is a helper method to define mock.On call
//   - params isConditionSetParams
func (_e *MockresourcesModel_Expecter) isConditionSet(params interface{}) *MockresourcesModel_isConditionSet_Call {
	return &MockresourcesModel_isConditionSet_Call{Call: _e.mock.On("isConditionSet", params)}
}

func (_c *MockresourcesModel_isConditionSet_Call) Run(run func(params isConditionSetParams)) *MockresourcesModel_isConditionSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(isConditionSetParams))
	})
	return _c
}

func (_c *MockresourcesModel_isConditionSet_Call) Return(_a0 bool) *MockresourcesModel_isConditionSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockresourcesModel_isConditionSet_Call) RunAndReturn(run func(isConditionSetParams) bool) *MockresourcesModel_isConditionSet_Call {
	_c.Call.Return(run)
	return _c
}

// setCondition provides a mock function with given fields: ctx, params
func (_m *MockresourcesModel) setCondition(ctx context.Context, params setConditionParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for setCondition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, setConditionParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockresourcesModel_setCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setCondition'
type MockresourcesModel_setCondition_Call struct {
	*mock.Call
}

// setCondition is a helper method to define mock.On call
//   - ctx context.Context
//   - params setConditionParams
func (_e *MockresourcesModel_Expecter) setCondition(ctx interface{}, params interface{}) *MockresourcesModel_setCondition_Call {
	return &MockresourcesModel_setCondition_Call{Call: _e.mock.On("setCondition", ctx, params)}
}

func (_c *MockresourcesModel_setCondition_Call) Run(run func(ctx context.Context, params setConditionParams)) *MockresourcesModel_setCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(setConditionParams))
	})
	return _c
}

func (_c *MockresourcesModel_setCondition_Call) Return(_a0 error) *MockresourcesModel_setCondition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockresourcesModel_setCondition_Call) RunAndReturn(run func(context.Context, setConditionParams) error) *MockresourcesModel_setCondition_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockresourcesModel creates a new instance of MockresourcesModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockresourcesModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockresourcesModel {
	mock := &MockresourcesModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
