// Code generated by mockery. DO NOT EDIT.

//go:build !release

package app

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockhttpBackendModel is an autogenerated mock type for the httpBackendModel type
type MockhttpBackendModel struct {
	mock.Mock
}

type MockhttpBackendModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockhttpBackendModel) EXPECT() *MockhttpBackendModel_Expecter {
	return &MockhttpBackendModel_Expecter{mock: &_m.Mock}
}

// syncBackendEndpoints provides a mock function with given fields: ctx, params
func (_m *MockhttpBackendModel) syncBackendEndpoints(ctx context.Context, params syncBackendEndpointsParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for syncBackendEndpoints")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, syncBackendEndpointsParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockhttpBackendModel_syncBackendEndpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'syncBackendEndpoints'
type MockhttpBackendModel_syncBackendEndpoints_Call struct {
	*mock.Call
}

// syncBackendEndpoints is a helper method to define mock.On call
//   - ctx context.Context
//   - params syncBackendEndpointsParams
func (_e *MockhttpBackendModel_Expecter) syncBackendEndpoints(ctx interface{}, params interface{}) *MockhttpBackendModel_syncBackendEndpoints_Call {
	return &MockhttpBackendModel_syncBackendEndpoints_Call{Call: _e.mock.On("syncBackendEndpoints", ctx, params)}
}

func (_c *MockhttpBackendModel_syncBackendEndpoints_Call) Run(run func(ctx context.Context, params syncBackendEndpointsParams)) *MockhttpBackendModel_syncBackendEndpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(syncBackendEndpointsParams))
	})
	return _c
}

func (_c *MockhttpBackendModel_syncBackendEndpoints_Call) Return(_a0 error) *MockhttpBackendModel_syncBackendEndpoints_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockhttpBackendModel_syncBackendEndpoints_Call) RunAndReturn(run func(context.Context, syncBackendEndpointsParams) error) *MockhttpBackendModel_syncBackendEndpoints_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockhttpBackendModel creates a new instance of MockhttpBackendModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockhttpBackendModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockhttpBackendModel {
	mock := &MockhttpBackendModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
