openapi: "3.0.0"
info:
  version: 1.0.0
  title: Minimalistic openapi starter
  description: |
    This is a minimalistic openapi starter template. Add your API definition as needed.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      tags:
        - health
      responses:
        '200':
          description: Request succeeded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponsePayload"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /echo:
    post:
      summary: Sample echo endpoint
      operationId: sendEcho
      tags:
        - echo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EchoRequestPayload'
        required: true
      responses:
        '200':
          description: Request succeeded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EchoResponsePayload"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    HealthResponsePayload:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - OK
    EchoRequestPayload:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    EchoResponsePayload:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    Error:
      type: object
      required:
        - code
      properties:
        code:
          format: string
        message:
          type: string