name: Docker Image

on:
  workflow_call:

jobs:
  build-image:
    name: Perform
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Required for multi-platform builds
    # https://docs.docker.com/build/building/multi-platform/#prerequisites
    - name: Set up Docker
      uses: docker/setup-docker-action@v4
      with:
        daemon-config: |
          {
            "features": {
              "containerd-snapshotter": true
            }
          }

    - uses: actions/download-artifact@v4
      with:
        name: build-artifacts-pr-${{ github.event.pull_request.node_id }}
        path: build

    - name: Extract build artifacts
      working-directory: build
      run: tar -xf build-artifacts.tar.bz2

    - name: Authenticate container registry
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare docker artifacts
      working-directory: build
      run: make docker-artifacts.tar.bz2
      env:
        GIT_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        GIT_REF: ${{ github.event.pull_request.head.ref }}

    - name: Upload docker artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docker-artifacts-pr-${{ github.event.pull_request.node_id }}
        path: build/docker-artifacts.tar.bz2
        retention-days: 7
        overwrite: true