name: Build Artifacts

on:
  workflow_call:

jobs:
  run:
    name: Prepare
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'

    - name: Setup Dependencies
      run: |
        go mod download
        go install tool

    - name: Build
      run: make build-artifacts.tar.bz2
      working-directory: build

    - name: Store artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-pr-${{ github.event.pull_request.node_id }}
        path: build/build-artifacts.tar.bz2
        retention-days: 7
        overwrite: true
