name: Build

on:
  release:
    types: [published]

permissions:
  contents: "read" # Needed for checkout
  packages: "write" # Needed to push to ghcr.io

jobs:
  release-tag-images:
    name: Release Tag Images
    uses: ./.github/workflows/release-tag-images.yml

  release-publish-helm:
    name: Release Publish Helm
    uses: ./.github/workflows/release-publish-helm.yml
