name: Build

# --- Testing Instructions ---
# To test this workflow manually:
# 1. Create PR with updates. Wait for CI to pass and docker images are available.
# 2. Create a latest release using the GitHub CLI using one of the commands:
#    gh release create v1.2.3 --latest --generate-notes --target "$(git branch --show-current)"
# 3. Ensure action is triggered and tagged images as follows: git-tag-v1.2.3 v1.2.3 v1.2-latest v1-latest latest
# 4. Create a pre-release using the GitHub CLI using one of the commands:
#    gh release create v1.2.3-rc --prerelease --generate-notes --target "$(git branch --show-current)"
# 5. Ensure action is triggered and tagged images as follows: git-tag-v1.2.3-rc v1.2.3-rc
# 6. Drop created releases and tags after testing is done using the following commands:
#    gh release delete v1.2.3-rc --yes --cleanup-tag
#    gh release delete v1.2.3 --yes --cleanup-tag
# --- End Testing Instructions ---

on:
  release:
    types: [published]

permissions:
  contents: "read" # Needed for checkout
  packages: "write" # Needed to push to ghcr.io

jobs:
  release-tag-images:
    name: Release Tag Images
    uses: ./.github/workflows/release-tag-images.yml

  release-publish-helm:
    name: Release Publish Helm
    uses: ./.github/workflows/release-publish-helm.yml
