name: Publish Helm

on:
  workflow_call:

jobs:
  publish:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Read Helm version
        id: helm-version
        run: echo "version=v$(cat deploy/.helm-version)" >> $GITHUB_OUTPUT

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ steps.helm-version.outputs.version }}

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package Helm chart
        working-directory: deploy
        run: |
          mkdir -p tmp
          helm package ./helm/controller/ -d tmp/

      - name: Get chart version
        id: chart
        working-directory: deploy
        run: |
          CHART_VERSION=$(helm show chart ./helm/controller/ | grep 'version:' | cut -d' ' -f2)
          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT

      - name: Push Helm chart
        working-directory: deploy
        run: |
          helm push tmp/oke-gateway-api-controller-${{ steps.chart.outputs.version }}.tgz oci://ghcr.io/gemyago/helm-charts

